/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FlightDetail: typeof import('./src/components/FlightDetail.vue')['default']
    ImageUploader: typeof import('./src/components/ImageUploader.vue')['default']
    LocationPicker: typeof import('./src/components/LocationPicker.vue')['default']
    MovieDetail: typeof import('./src/components/MovieDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScenicDetail: typeof import('./src/components/ScenicDetail.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    TicketCard: typeof import('./src/components/TicketCard.vue')['default']
    TrainDetail: typeof import('./src/components/TrainDetail.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanTag: typeof import('vant/es')['Tag']
  }
}
